# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    http_method_override: false


    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native


    php_errors:
        log: true

# Aqui le estamos indicando que los grupos de serializacion estan en esta carpeta
    serializer:
        mapping:
            path:
                - '%kernel.project_dir%/config/api_platform/serialization'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
